name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: metapic
          MYSQL_USER: metapic
          MYSQL_PASSWORD: metapic
          MYSQL_DATABASE: example
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm clean-install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Lint and test example
        env:
          DB_HOST: localhost
        run: |
          pushd example
          npm clean-install
          npm run lint
          npm run test
          popd

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
